"""Kernel audit report generation package"""

from report.base_report import (
    STREAMLIT_AVAILABLE,
    build_kev_data,
    build_report_data,
    build_sandbox_runs,
    build_security_recommendations,
    fetch_all_vulnerabilities,
    get_kernel_info,
    get_scan_times,
    load_report_json,
    main,
    main_cli,
    save_report_json,
    sort_vulnerabilities,
)
from report.cli import CLIReportRenderer
from report.diff import (
    build_caps_diff,
    build_diff,
    build_diff_columns,
    build_hardening_diff,
    build_module_diff,
    build_param_diff,
    build_selinux_diff,
    build_two_column,
    collect_sandbox_modules,
    count_findings,
    host_module_names,
    host_module_set,
    host_param_map,
    host_selinux_map,
    load_selinux_params,
)
from report.streamlit_rep import StreamlitReportRenderer

__all__ = [
    "STREAMLIT_AVAILABLE",
    "CLIReportRenderer",
    "StreamlitReportRenderer",
    "build_caps_diff",
    "build_diff",
    "build_diff_columns",
    "build_hardening_diff",
    "build_kev_data",
    "build_module_diff",
    "build_param_diff",
    "build_report_data",
    "build_sandbox_runs",
    "build_security_recommendations",
    "build_selinux_diff",
    "build_two_column",
    "collect_sandbox_modules",
    "count_findings",
    "fetch_all_vulnerabilities",
    "get_kernel_info",
    "get_scan_times",
    "host_module_names",
    "host_module_set",
    "host_param_map",
    "host_selinux_map",
    "load_report_json",
    "load_selinux_params",
    "main",
    "main_cli",
    "save_report_json",
    "sort_vulnerabilities",
]